### ISSUE TITLE
ps3 and xbox 360 support for bf4 

### ISSUE THREAD

**Issue by BlackGhost3** [MattMcFarland/battlefield-stats#2]
does the api support **ps3** and **xbox360** stats for bf4 ?
and is battlefield hardline stats supported ?

**Comment by MattMcFarland** [comment]
Yep, this is using battlefield tracker which supports those as well.

**Comment by BlackGhost3** [comment]
platform: bf.Platforms.xbox360
platform: bf.Platforms.XBOX360
platform: bf.Platforms.ps3
platform: bf.Platforms.PS3
those platforms are returning  `AssertionError: platform is required: null`

**Comment by MattMcFarland** [comment]
Here are the available platform options:
bf.Platforms.XBOX
bf.Platforms.PC
bf.Platforms.PS4

`bf.Platforms.PS4` is a mistake and will be renamed to `bf.Platforms.PSN` at a later time.

**Comment by BlackGhost3** [comment]
so xbox 360 and ps3 are not supported ?
